###############
## 
####

GPU: [0,1,2,3]

VERBOSE: True

MODEL:
  MODE: 'Deblurring'
  SESSION: ''

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 16
  NUM_EPOCHS: 300
  # NEPOCH_DECAY: [10]
  LR_INITIAL: 0.00005
  LR_MIN: 1e-6
  # BETA1: 0.9

TRAINING:
  VAL_AFTER_EVERY: 1
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 256
  TRAIN_DIR: '' # path to training data
  VAL_DIR: ''   # path to validation data
  SAVE_DIR: ''     # path to save models and images
  # SAVE_IMAGES: False

TESTING:
  TEST_PS : 256
#  TEST_DIR: ''   # path to validation data
